site_name: "2022-2-EuPescador-Doc"

theme:
  logo: assets/logo/logoNova.jpg
  favicon: assets/logo/logoNova.jpg
  name: material
  language: "pt"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Sobre: index.md
  - Produto:
    - EAP: produto/eap.md
    - Identidade Visual: produto/identidade_visual.md
  - Gestão da equipe:
    - Quadro de Conhecimentos: organizacao/conhecimentos.md
    - Comunicacao: organizacao/comunicacao.md
    - Horarios: organizacao/horarios.md
    - Gerenciamento de Riscos: organizacao/riscos.md
  - Atas:
    - Reunião com o time:
      - Ata (10/11/2022): atas/reuniao-com-time/ata_10_11_22.md
      - Ata (17/11/2022): atas/reuniao-com-time/ata_17_11_22.md
      - Ata (19/11/2022): atas/reuniao-com-time/ata_19_11_22.md
      - Ata (23/11/2022): atas/reuniao-com-time/ata_23_11_22.md
    - Reunião com o cliente:
      - Ata (11/11/2022): atas/reuniao-com-cliente/ata_11_11_22.md
      - Ata (18/11/2022): atas/reuniao-com-cliente/ata_18_11_22.md
      - Ata (28/11/2022): atas/reuniao-com-cliente/ata_28_11_22.md
