site_name: "2022-2-EuPescador-Doc"

theme:
  name: material
  language: "pt"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Sobre: index.md